#!/bin/bash

if [ -e /sys/firmware/efi ]
then
  zenity --info --text="EFI Detected \n \n Auto install is not yet available \n Goes on https://github.com/linuxconsole-org/ydfs2/blob/2.12/TIPS.md for more info" &>/dev/null
  exit 1
fi

LIST_DISK=""

for device in `ls /sys/class/block/`
do
  [ -e /sys/class/block/$device/partition ] && continue
  [ $(cat /sys/class/block/$device/removable) = "1" ] && continue
  echo $device |grep loop >/dev/null && continue
  SIZE=$(LC_ALL=EN fdisk -l /dev/$device |grep sector |head -1 |  gawk '{print $3}' |sed s@' '@_@g)
  # MODEL=$(LC_ALL=EN fdisk -l /dev/$device |grep model |cut -d':' -f2|sed s@' '@_@g)
  MODEL=$(LC_ALL=EN fdisk -l /dev/$device |grep model |gawk '{print $3}')
  [ "$MODEL" = "" ] && MODEL="-"
  LIST_DISK="$LIST_DISK FALSE $device $MODEL $SIZE"
done

echo $LIST_DISK

if [ "$LANG" = "fr_FR.UTF8" ]
then
DISK=$(zenity  --width=600 --height=300  --list --text "Disque où installer GRUB :" --radiolist --column "Choix"  --column "Disque" --column "Nom" --column "Taille" $LIST_DISK)
[ "$DISK" = "" ] && zenity --info --text="Abandon !" &&  exit 0
else
DISK=$(zenity  --width=600 --height=300  --list --text "Disk where you want to install GRUB :" --radiolist --column "Choice"  --column "Disk" --column "Name" --column "Size" $LIST_DISK)
[ "$DISK" = "" ] && zenity --info --text="Cancelled !" &&  exit 0
fi

echo Install on $DISK

DISTRONAME=`cat /ydfs-name`
if [ ! -e /dev/$DISK ]
then
  zenity --info --text="You need a /dev/"$DISK" disk for this !" &>/dev/null
  exit 1	  
else
  if [ -e /dev/"$DISK"1 ]
	then
           zenity --question --text="Warning, grub will be installed on your /dev/"$DISK" disk ! Are you sure ?" &>/dev/null
	   ans=$?
	   echo $ans  
	   [ "$ans" != "0" ] && exit 1
	fi
fi

if [ ! -e /media/$DISTRONAME ]
then
which gpartedbin || opkg-cl install gparted
zenity --info --text="Please create a partition named $DISTRONAME \n\nClose this, gparted will start" &>/dev/null

if [ -e /sys/firmware/efi ]
then
  zenity --info --text="EFI Detected \n \n Please first create a FAT32 BOOT partition, and copy EFI, isolinux, boot \n Also remove the liveusb option from /boot/grub/grub.cfg" &>/dev/null
fi

echo "Please wait ..."
# To disable remounting while running gparted
echo > /usr/lib/udev/rules.d/11-media-by-label-auto-mount.rules
udevadm trigger --action=add
$HOME_DIBAB/$ARCH/sbin/gpartedbin &>/dev/null
sh /ydfs/start/automount
sleep 1
udevadm trigger --action=add
sleep 3
  if [ ! -e /media/$DISTRONAME ]
  then
	  zenity --error --text="Please format an ext4 partition with $DISTRONAME lablel !" &>/dev/null
  	exit 1
  fi
fi

if [ ! -e /sys/firmware/efi ]
then
  [ ! -e /boot ] && ln -sf /media/$DISTRONAME /boot
  grub-install /dev/"$DISK"  --boot-directory=/media/$DISTRONAME || grub-install /dev/"$DISK"  --boot-directory=/media/$DISTRONAME || exit 1
  echo "Installing kernel and initramfs"
  mkdir /media/$DISTRONAME/rootfs
  KVER=`uname -r`
  cp /media/ydfs/isolinux/kernel /boot/kernel-$KVER
  cp /media/ydfs/isolinux/initramfs /boot/initramfs-genkernel-$KVER
  cp /proc/config.gz /boot
  gunzip /boot/config.gz
  mv /boot/config /boot/config-$KVER
  sed -i 's@target=device /`@target=device /media/DISTRONAME`@'  `which grub-mkconfig`
  sed -i "s@DISTRONAME@$DISTRONAME@"  `which grub-mkconfig`
  echo "running grub-mkconfig"
  find /sys |grep "$DISK"|grep usb && BOOTOPTION=" liveusb "
  LC_ALL=en_US.UTF8 grub-mkconfig -o /media/$DISTRONAME/grub/grub.cfg
  [ -e /media/$DISTRONAME/grub/grub.cfg.new ] && cp /media/$DISTRONAME/grub/grub.cfg.new /media/$DISTRONAME/grub/grub.cfg
  sed -i "s@ ro @$BOOTOPTION ro quiet loglevel=0 @" /media/$DISTRONAME/grub/grub.cfg
  touch /media/$DISTRONAME/syslinux.cfg # used for mount partition as DISTRONAME disk
else
  touch /media/$DISTRONAME/syslinux.cfg # used for mount partition as DISTRONAME disk
fi

echo "Copying module ..."
ls /media/ydfs/modules/ | while read file
do
	echo $file
	install -d /media/$DISTRONAME/modules
  cp /media/ydfs/modules/$file /media/$DISTRONAME/modules
done
if [ -e /media/ydfs/pkg/ ]
then
echo "Copying packages ..."
ls /media/ydfs/pkg/ | while read file
do
	echo $file
	install -d /media/$DISTRONAME/pkg
  cp /media/ydfs/pkg/$file /media/$DISTRONAME/pkg
done
fi
  zenity --info --text="Installation finished, you can reboot now" &>/dev/null
