#!/busybox/bin/sh

/busybox/bin/mkdir /ydfs/boot/
/busybox/bin/mkdir /ydfs/boot/options

for OPTION in `/busybox/bin/cat /proc/cmdline`
do
  case $OPTION in 
    kbd=*) 
	/busybox/sbin/loadkmap < /share/kmap/$kbd.kmap ;;
  esac
	echo $OPTION | /busybox/bin/grep "=" >/dev/null && continue
	/busybox/bin/mkdir /ydfs/boot/options/$OPTION
done

[ -e /ydfs/boot/options/fr ] && /busybox/sbin/loadkmap < /share/kmap/azerty.kmap
[ -e /ydfs/boot/options/azerty ] && /busybox/sbin/loadkmap < /share/kmap/azerty.kmap

/busybox/bin/echo -n "Boot options : "
/busybox/bin/ls /ydfs/boot/options
