#!/busybox/bin/sh

/busybox/bin/mkdir /ydfs/boot/
/busybox/bin/mkdir /ydfs/boot/options

for OPTION in `/busybox/bin/cat /proc/cmdline`
do
  case $OPTION in 
    kbd=*) 
	/busybox/sbin/loadkmap < /share/kmap/$kbd.kmap ;;
  esac
	echo $OPTION | /busybox/bin/grep "=" >/dev/null && continue
	/busybox/bin/mkdir /ydfs/boot/options/$OPTION
done

[ -e /ydfs/boot/options/fr ] && /busybox/sbin/loadkmap < /share/kmap/azerty.kmap
[ -e /ydfs/boot/options/azerty ] && /busybox/sbin/loadkmap < /share/kmap/azerty.kmap

/busybox/bin/echo -n "Boot options : "
/busybox/bin/ls /ydfs/boot/options

if [ -e /ventoy/hook/debian/linuxconsole-disk.sh ]
then
  #echo "Ventoy detected, but currently need to be improved for Your Distro From Scracth > 2.11 " > /dev/tty1
  #echo "If it fails, You can try https://github.com/Mexit/MultiOS-USB to use more ISOs on your USB Disk" > /dev/tty1
  cp /fix/linuxconsole-disk.sh /ventoy/hook/debian/linuxconsole-disk.sh
fi

