#!/busybox/bin/ash

[ ! -e /proc/stat ] && /busybox/bin/mount /proc proc -t proc

. /ydfs/detect/boot_options

[ -e /ydfs/boot/options/debug01  ] && echo /busybox/bin/echo /ydfs/boot/options/debug01 && /busybox/bin/ash

. /etc/profile

[ ! -e /sys/kernel ] && mount /sys sys -t sysfs
mount -t devtmpfs none /dev

[ ! -e /dev/pts ] && mkdir /dev/pts
mount devpts /dev/pts -t devpts

ln -s /proc/mounts /etc/mtab # For Gparted

if [ -e /ydfs/boot/options/ash  ]; then
/busybox/bin/ash 
fi

ln -s /ydfs /dibab
[ -e /ydfs/boot/options/debug02  ] && sh

echo -n "Detect media"

. /ydfs/detect/media

[ -e /ydfs/boot/options/debug03  ] && sh

echo -n "Mount ydfs modules"
. /ydfs/detect/modules

[ -e /ydfs/boot/options/debug04  ] && sh

# [ ! -e /ydfs/boot/options/nofcc ] && echo -n "Start font cache .. " && /ydfs/enable/fonts && echo "ok"
[ -e /ydfs/boot/options/fcc ] && echo -n "Start font cache .. " && /ydfs/enable/fonts

. /ydfs/start/fixydfs

[ -e /ydfs/boot/options/debug05  ] && sh
. /ydfs/start/automount
. /ydfs/start/mountopt
[ -e /ydfs/boot/options/debug06  ] && sh
echo "Detect hardware"
. /ydfs/detect/hardware
[ -e /ydfs/boot/options/debug07  ] && sh
echo "Detect Network"
. /ydfs/detect/network & #> /dev/tty2 2>/dev/tty2

# echo "Set up sound mixer"

. /ydfs/detect/mixer &
. /ydfs/enable/swap &
. /ydfs/detect/cups &
# . /ydfs/detect/wireless &

[ -e /ydfs/boot/options/debug08  ] && sh

if [ -e /ydfs/boot/options/fixusb  ]; then 
echo "FIXUSB mode, looking into usb disks ..." && sleep 9
. /ydfs/start/fixusb || ash
fi

if [ -e /ydfs/boot/options/fixme  ]; then 
echo "FIXME mode" && sleep 5
. /ydfs/start/fixme || ash
fi

if [ -e /ydfs/boot/options/benchmark  ]; then 
echo "Benchmark" && sleep 5
. /ydfs/start/benchmark || ash
fi

# . /ydfs/enable/virtualbox

. /ydfs/enable/flatpak-disk

/fix/libs

[ -e /media/ydfs/pkg ] && echo "Opkg update" && opkg-cl update

date > /tmp/xorg-start-date

if [ -e /ydfs/boot/options/text  ]; then
  echo "You can now start /ydfs/start/xorg"
  sh
else
  echo "Start Xorg"
  /ydfs/start/xorg
fi

# /ydfs/start/save-persistant-data

[ -e /ydfs/boot/options/debug09  ] && sh

busybox sh /ydfs/stop/all

echo "Stoping all process ... "
touch /tmp/stop
killall5 

[ -e /ydfs/boot/options/debug10  ] && sh
echo -n "Stoping network interfaces ... "
ls /sys/class/net/| while read NET
do
echo -n "$NET "
ifconfig $NET down 1>/dev/null 2>/dev/null
done

/sbin/swapoff -a
/busybox/bin/umount -l /dev
sync
sleep 1
echo
/busybox/bin/umount /usr/var/cache/fontconfig
/busybox/bin/umount /usr/var

[ $? != 0 ] && [ -e /ydfs/boot/options/debugpoweroff ] && echo "debugpoweroff mode on" && /busybox/bin/ash
/busybox/bin/umount -a >/dev/null 2>/dev/null
lsof | grep usr
if [ $? = 0 ] 
then
 echo "Error when umounting all" > /dev/tty1
 lsof | grep usr > /dev/tty1 
 sleep 10
 [ -e /ydfs/boot/options/debugpoweroff ] && echo "debugpoweroff mode on" && /busybox/bin/ash
else
 echo "umounting : done" > /dev/tty1
fi

[ -e /ydfs/boot/options/debug11  ] && sh

[ -e /media/ydfs/modules ] && [ -e /ydfs/boot/options/debugpoweroff ] && mount && echo "error while umount, run poweroff yourself" && /busybox/bin/ash

if [ -e /var/ydfs/boot/media/cdrom/ ]
then
  mount -t devtmpfs none /dev
  echo "Ejecting cdrom, 5 seconds before poweroff" > /dev/tty1
  eject -s /dev/`ls /var/ydfs/boot/media/cdrom/`
  sleep 5
fi

[ -e /ydfs/boot/options/debug12  ] && sh
[ -e /run-before-poweroof  ] && sh /run-before-poweroof

[ -e /var/log/ConsoleKit/history ] && grep RESTART /var/log/ConsoleKit/history && echo "Rebooting" && reboot
echo "Poweroff"
poweroff
