#!/bin/bash

if [ -e /disk/flatpak.loop ]
then
  echo "Enable /disk/flatpak.loop"

  install -d /flatpak
  mount /disk/flatpak.loop /flatpak -o loop
  [ -e /flatpak/lost+found ] && rmdir /flatpak/lost+found
  ln -sf /flatpak /home/linuxconsole2026/x86_64/var/lib/flatpak

  install -d /flatpak/root/.var/app
  install -d /root/.var
  ln -s  /flatpak/root/.var/app /root/.var/
fi
  
install -d /flatpak/home     
ls /home | while read home
do
  echo $home | grep linuxconsole && continue
  if [ ! -e /flatpak/home/$home ] 
  then
      mv /home/$home /flatpak/home && ln -s /flatpak/home/$home /home/$home
  else
      mv /home/$home /home/$home.old
      ln -s /flatpak/home/$home /home/$home
  fi
done   

